description = "Class 66 Freight example"
units = ["Class66", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA", "FEA"]

[activities.attach]
min = 240
max = 360

[activities.detach]
min = 180
max = 300

[activities.reverse]
min = 90
max = 150