[manifest]
id = "west-kestby-renewal"
name = "West Kestby Renewal Project"
version = "0.2.0"
author = "beewuzzer"

[target]
game = "^0.1.0"
sim = "kestby"
sim_version = "^0.1.0"

[timing]
timing_mode = "tiploc"
tiploc = "KESTBY"
occurrence = 1
