[template]
description = "Kestby P2 to P3"

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
plat = 2

[[simulation.point]]
tiploc = "KSTBY28"
activities = ["reverse"]
dwell = "2H"
path = "DM"

[[simulation.point]]
tiploc = "KESTBY"
plat = 3

[simulation.terminates]