[template]
description = "Kestby P1 to P2"

[simulation]

[[simulation.point]]
tiploc = "KESTBY"
plat = 2

[[simulation.point]]
tiploc = "KSTBY28"
activities = ["reverse"]
dwell = "2H"
path = "DM"

[[simulation.point]]
tiploc = "KESTBY"
plat = 1
path = "UM"

[simulation.terminates]