[staticTemplate]
description = "Fast TPE Diversionary Route (Aireborough to Anserham Central)"
timing_load = "100mph Desiro 185"

[beforeSimulatedArea]
AIB = { travel_time = "10H", dwell = "0H" }
MTF = { travel_time = "18", dwell = "0H" }

[afterSimulatedArea]
ANC = { travel_time = "50H", dwell = "0H" }
