[diagram]
operator = "West Coast Railways"
allocation = [
    { consist = "47", weight = 100 }
]

allow_early = true

[[service]] 
headcode = "1Z99"
template = "BranchKestby" 
departs = "0935" 
signaller_permission = true
do_not_advertise = true
[service.static] 
template = "1Z99" 
[service.timing]
profile = "Freight"
[[service.static.exception]]
crs = "WRW"
exclude = true
[[service.exception]]
tiploc = "KESTBY"
plat = 2
path = "DM"
[[service.exception]]
tiploc = "KMTHHALT"
pass = true

[[service]] 
headcode = "1Z99"
template = "KestbyBranch" 
departs = "0945" 
signaller_permission = true
do_not_advertise = true
[service.static] 
template = "1Z99" 
reversed = true
[[service.exception]]
tiploc = "KMTHHALT"
pass = true
[[service.exception]]
tiploc = "KESTBY"
plat = 2
[[service.activity.attach]]
tiploc = "KESTBY"
joins = "1T08"
[service.timing]
profile = "Freight"