[staticTemplate]
description = "Northern Diversionary Route (Kestby to Anserham Agincourt Square)"
timing_load = "75mph Super Sprinter 150/153/155/156"

[afterSimulatedArea]
WGL = { travel_time = "4H", dwell = "0H" }
STE = { travel_time = "3H", dwell = "0H" }
ELD = { travel_time = "4H", dwell = "0H" }
BNC = { travel_time = "5H", dwell = "0H" }
BBR = { travel_time = "4H", dwell = "0H" }
AAS = { travel_time = "45", dwell = "0H" }